swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /reservation/{carparkName}/{pin}/{lower}:
    get:
      operationId: "reservation.move_cone"
      tags:
        - "reservation"
      summary: "The people data structure supported by the server application"
      description: "Move the cone"
      parameters:
        - name: carparkName
          in: path
          description: ID of parking lot to be reserved
          type: string
          required: True
        - name: pin
          in: path
          description: Pin on the raspberry pi to lower down / raise up the cone
          type: integer
          required: True
        - name: lower
          in: path
          description: Lowering of cone
          type: boolean
          required: True

      responses:
        200:
          description: "Cone moved succesfully"
          schema:
            type: string

  /reservation-expired/{carparkName}/{pin}/{expired}:
    get:
      operationId: "reservation.lower_cone"
      tags:
        - "reservation"
      summary: "The people data structure supported by the server application"
      description: "Lower the cone for expired reservation"
      parameters:
        - name: carparkName
          in: path
          description: ID of parking lot to be reserved
          type: string
          required: True
        - name: pin
          in: path
          description: Pin on the raspberry pi to lower down / raise up the cone
          type: integer
          required: True
        - name: expired
          in: path
          description: Validity status of the reservation
          type: boolean
          required: True

      responses:
        200:
          description: "Cone lowered succesfully for expired reservation"
          schema:
            type: string
